/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotarIndexRouteImport } from './routes/votar.index'
import { Route as VotarConfirmadoRouteImport } from './routes/votar.confirmado'
import { Route as VotarCedulaRouteImport } from './routes/votar.cedula'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarIndexRoute = VotarIndexRouteImport.update({
  id: '/votar/',
  path: '/votar/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarConfirmadoRoute = VotarConfirmadoRouteImport.update({
  id: '/votar/confirmado',
  path: '/votar/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarCedulaRoute = VotarCedulaRouteImport.update({
  id: '/votar/cedula',
  path: '/votar/cedula',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar/': typeof VotarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar': typeof VotarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar/': typeof VotarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VotarCedulaRoute: typeof VotarCedulaRoute
  VotarConfirmadoRoute: typeof VotarConfirmadoRoute
  VotarIndexRoute: typeof VotarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/': {
      id: '/votar/'
      path: '/votar'
      fullPath: '/votar/'
      preLoaderRoute: typeof VotarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/confirmado': {
      id: '/votar/confirmado'
      path: '/votar/confirmado'
      fullPath: '/votar/confirmado'
      preLoaderRoute: typeof VotarConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/cedula': {
      id: '/votar/cedula'
      path: '/votar/cedula'
      fullPath: '/votar/cedula'
      preLoaderRoute: typeof VotarCedulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VotarCedulaRoute: VotarCedulaRoute,
  VotarConfirmadoRoute: VotarConfirmadoRoute,
  VotarIndexRoute: VotarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
