/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CandidatarRouteImport } from './routes/candidatar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotarIndexRouteImport } from './routes/votar.index'
import { Route as VotarConfirmadoRouteImport } from './routes/votar.confirmado'
import { Route as VotarCedulaRouteImport } from './routes/votar.cedula'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEmpregadosRouteImport } from './routes/_authenticated/admin.empregados'
import { Route as AuthenticatedAdminEleicoesRouteImport } from './routes/_authenticated/admin.eleicoes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAtasRouteImport } from './routes/_authenticated/admin.atas'
import { Route as AuthenticatedAdminEleicoesIdRouteImport } from './routes/_authenticated/admin.eleicoes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatarRoute = CandidatarRouteImport.update({
  id: '/candidatar',
  path: '/candidatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarIndexRoute = VotarIndexRouteImport.update({
  id: '/votar/',
  path: '/votar/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarConfirmadoRoute = VotarConfirmadoRouteImport.update({
  id: '/votar/confirmado',
  path: '/votar/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const VotarCedulaRoute = VotarCedulaRouteImport.update({
  id: '/votar/cedula',
  path: '/votar/cedula',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmpregadosRoute =
  AuthenticatedAdminEmpregadosRouteImport.update({
    id: '/empregados',
    path: '/empregados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEleicoesRoute =
  AuthenticatedAdminEleicoesRouteImport.update({
    id: '/eleicoes',
    path: '/eleicoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAtasRoute = AuthenticatedAdminAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEleicoesIdRoute =
  AuthenticatedAdminEleicoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEleicoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidatar': typeof CandidatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar/': typeof VotarIndexRoute
  '/admin/atas': typeof AuthenticatedAdminAtasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eleicoes': typeof AuthenticatedAdminEleicoesRouteWithChildren
  '/admin/empregados': typeof AuthenticatedAdminEmpregadosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/eleicoes/$id': typeof AuthenticatedAdminEleicoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidatar': typeof CandidatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar': typeof VotarIndexRoute
  '/admin/atas': typeof AuthenticatedAdminAtasRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eleicoes': typeof AuthenticatedAdminEleicoesRouteWithChildren
  '/admin/empregados': typeof AuthenticatedAdminEmpregadosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/eleicoes/$id': typeof AuthenticatedAdminEleicoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/candidatar': typeof CandidatarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/votar/cedula': typeof VotarCedulaRoute
  '/votar/confirmado': typeof VotarConfirmadoRoute
  '/votar/': typeof VotarIndexRoute
  '/_authenticated/admin/atas': typeof AuthenticatedAdminAtasRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/eleicoes': typeof AuthenticatedAdminEleicoesRouteWithChildren
  '/_authenticated/admin/empregados': typeof AuthenticatedAdminEmpregadosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/eleicoes/$id': typeof AuthenticatedAdminEleicoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidatar'
    | '/reset-password'
    | '/admin'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar/'
    | '/admin/atas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/eleicoes'
    | '/admin/empregados'
    | '/admin/'
    | '/admin/eleicoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidatar'
    | '/reset-password'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar'
    | '/admin/atas'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/eleicoes'
    | '/admin/empregados'
    | '/admin'
    | '/admin/eleicoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/candidatar'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/votar/cedula'
    | '/votar/confirmado'
    | '/votar/'
    | '/_authenticated/admin/atas'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/eleicoes'
    | '/_authenticated/admin/empregados'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/eleicoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CandidatarRoute: typeof CandidatarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VotarCedulaRoute: typeof VotarCedulaRoute
  VotarConfirmadoRoute: typeof VotarConfirmadoRoute
  VotarIndexRoute: typeof VotarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatar': {
      id: '/candidatar'
      path: '/candidatar'
      fullPath: '/candidatar'
      preLoaderRoute: typeof CandidatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/': {
      id: '/votar/'
      path: '/votar'
      fullPath: '/votar/'
      preLoaderRoute: typeof VotarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/confirmado': {
      id: '/votar/confirmado'
      path: '/votar/confirmado'
      fullPath: '/votar/confirmado'
      preLoaderRoute: typeof VotarConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votar/cedula': {
      id: '/votar/cedula'
      path: '/votar/cedula'
      fullPath: '/votar/cedula'
      preLoaderRoute: typeof VotarCedulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empregados': {
      id: '/_authenticated/admin/empregados'
      path: '/empregados'
      fullPath: '/admin/empregados'
      preLoaderRoute: typeof AuthenticatedAdminEmpregadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eleicoes': {
      id: '/_authenticated/admin/eleicoes'
      path: '/eleicoes'
      fullPath: '/admin/eleicoes'
      preLoaderRoute: typeof AuthenticatedAdminEleicoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/atas': {
      id: '/_authenticated/admin/atas'
      path: '/atas'
      fullPath: '/admin/atas'
      preLoaderRoute: typeof AuthenticatedAdminAtasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eleicoes/$id': {
      id: '/_authenticated/admin/eleicoes/$id'
      path: '/$id'
      fullPath: '/admin/eleicoes/$id'
      preLoaderRoute: typeof AuthenticatedAdminEleicoesIdRouteImport
      parentRoute: typeof AuthenticatedAdminEleicoesRoute
    }
  }
}

interface AuthenticatedAdminEleicoesRouteChildren {
  AuthenticatedAdminEleicoesIdRoute: typeof AuthenticatedAdminEleicoesIdRoute
}

const AuthenticatedAdminEleicoesRouteChildren: AuthenticatedAdminEleicoesRouteChildren =
  {
    AuthenticatedAdminEleicoesIdRoute: AuthenticatedAdminEleicoesIdRoute,
  }

const AuthenticatedAdminEleicoesRouteWithChildren =
  AuthenticatedAdminEleicoesRoute._addFileChildren(
    AuthenticatedAdminEleicoesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAtasRoute: typeof AuthenticatedAdminAtasRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEleicoesRoute: typeof AuthenticatedAdminEleicoesRouteWithChildren
  AuthenticatedAdminEmpregadosRoute: typeof AuthenticatedAdminEmpregadosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAtasRoute: AuthenticatedAdminAtasRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEleicoesRoute: AuthenticatedAdminEleicoesRouteWithChildren,
  AuthenticatedAdminEmpregadosRoute: AuthenticatedAdminEmpregadosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CandidatarRoute: CandidatarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VotarCedulaRoute: VotarCedulaRoute,
  VotarConfirmadoRoute: VotarConfirmadoRoute,
  VotarIndexRoute: VotarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
